name: var
description: Blogging about stuff
meta_description: "var thoughts"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'sotirop.github.io'
author:         'Aris Sotiropoulos'
